"""yo

Revision ID: 801ae74ce1f5
Revises: 
Create Date: 2026-03-10 17:13:21.281296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '801ae74ce1f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Safe for fresh or existing DB."""
    op.drop_table('party_member_positions', if_exists=True)
    op.drop_table('party_members', if_exists=True)
    op.drop_table('parties', if_exists=True)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    if 'region_counters' not in tables:
        op.create_table('region_counters',
            sa.Column('region', sa.String(), primary_key=True),
            sa.Column('next_number', sa.Integer(), nullable=False),
        )
    if 'queues' not in tables:
        op.create_table('queues',
            sa.Column('queue_id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('queue_code', sa.String(), nullable=False, unique=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('region', sa.String(), nullable=False),
            sa.Column('max_players', sa.Integer(), nullable=False),
            sa.Column('players_in_queue', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        )
    if 'queue_slot' not in tables:
        op.create_table('queue_slot',
            sa.Column('slot_id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('queue_id', sa.Integer(), sa.ForeignKey('queues.queue_id'), nullable=False),
            sa.Column('team', sa.String(), nullable=False),
            sa.Column('position', sa.String(), nullable=False),
            sa.Column('slot_number', sa.Integer(), nullable=False),
            sa.Column('occupant_user_id', sa.BigInteger(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
        )
    if 'queue_players' not in tables:
        op.create_table('queue_players',
            sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('user_id', sa.BigInteger(), nullable=False),
            sa.Column('queue_id', sa.Integer(), sa.ForeignKey('queues.queue_id'), nullable=False),
            sa.Column('party_id', sa.String(), nullable=True),
            sa.Column('assigned_slot_id', sa.Integer(), sa.ForeignKey('queue_slot.slot_id'), nullable=False),
            sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        )
    if 'matches' not in tables:
        op.create_table('matches',
            sa.Column('match_id', sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column('queue_id', sa.Integer(), sa.ForeignKey('queues.queue_id'), nullable=False),
            sa.Column('match_code', sa.String(), nullable=False, unique=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('region', sa.String(), nullable=False),
            sa.Column('place_id', sa.BigInteger(), nullable=False),
            sa.Column('reserved_server_code', sa.String(), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        )
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'queue_players') THEN
                ALTER TABLE queue_players DROP CONSTRAINT IF EXISTS queue_players_party_id_fkey;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region_counters', type_='unique')
    op.drop_constraint(None, 'queues', type_='unique')
    op.drop_constraint(None, 'queue_slot', type_='unique')
    op.create_foreign_key(op.f('queue_players_party_id_fkey'), 'queue_players', 'parties', ['party_id'], ['party_id'])
    op.drop_constraint(None, 'queue_players', type_='unique')
    op.drop_constraint(None, 'matches', type_='unique')
    op.create_table('party_member_positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name=op.f('party_member_positions_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('party_member_positions_pkey'))
    )
    op.create_table('party_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name=op.f('party_members_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('party_members_pkey'))
    )
    op.create_table('parties',
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('party_id', name=op.f('parties_pkey')),
    sa.UniqueConstraint('party_code', name=op.f('parties_party_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
