"""yo

Revision ID: 801ae74ce1f5
Revises: 
Create Date: 2026-03-10 17:13:21.281296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '801ae74ce1f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_member_positions', if_exists=True)
    op.drop_table('party_members', if_exists=True)
    op.drop_table('parties', if_exists=True)
    op.create_unique_constraint(None, 'matches', ['match_id'])
    op.create_unique_constraint(None, 'queue_players', ['id'])
    op.drop_constraint(op.f('queue_players_party_id_fkey'), 'queue_players', type_='foreignkey')
    op.create_unique_constraint(None, 'queue_slot', ['slot_id'])
    op.create_unique_constraint(None, 'queues', ['queue_id'])
    op.create_unique_constraint(None, 'region_counters', ['region'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region_counters', type_='unique')
    op.drop_constraint(None, 'queues', type_='unique')
    op.drop_constraint(None, 'queue_slot', type_='unique')
    op.create_foreign_key(op.f('queue_players_party_id_fkey'), 'queue_players', 'parties', ['party_id'], ['party_id'])
    op.drop_constraint(None, 'queue_players', type_='unique')
    op.drop_constraint(None, 'matches', type_='unique')
    op.create_table('party_member_positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name=op.f('party_member_positions_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('party_member_positions_pkey'))
    )
    op.create_table('party_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name=op.f('party_members_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('party_members_pkey'))
    )
    op.create_table('parties',
    sa.Column('party_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('party_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('party_id', name=op.f('parties_pkey')),
    sa.UniqueConstraint('party_code', name=op.f('parties_party_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
