#!/usr/bin/env python
"""
Generate example payload dicts from Admin.schemas.
Run from project root: python scripts/generate_payload_examples.py
Outputs to docs/PAYLOAD_EXAMPLES.txt
"""
import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from Admin import schemas


def example_from_model(model_class, name: str) -> dict:
    """Build example dict from Pydantic model using schema and defaults."""
    s = model_class.model_json_schema()
    props = s.get("properties", {})
    required = set(s.get("required", []))
    result = {}
    for key, spec in props.items():
        default = spec.get("default")
        if default is not None:
            result[key] = default
        elif "enum" in spec:
            result[key] = spec["enum"][0]
        elif spec.get("type") == "string":
            result[key] = spec.get("examples", [spec.get("minLength", 1) * "x"])[0] if "examples" in spec else ""
        elif spec.get("type") == "integer":
            result[key] = spec.get("minimum", 0)
        elif spec.get("type") == "array":
            items = spec.get("items", {})
            if "enum" in items:
                result[key] = [items["enum"][0]]
            else:
                result[key] = []
        elif spec.get("anyOf"):
            for opt in spec["anyOf"]:
                if "type" in opt and opt["type"] == "null":
                    result[key] = None
                    break
            else:
                result[key] = None
        else:
            result[key] = None
    return result


def main():
    examples = {
        "SoloJoinRequest": {
            "regular": {
                "user_id": 123456789,
                "region": "EU",
                "positions": ["CB", "GK"],
                "team_format": "5v5",
                "queue_type": "regular",
                "ranked_tier": None,
                "player_level": 42,
            },
            "ranked": {
                "user_id": 123456789,
                "region": "EU",
                "positions": ["CB", "GK"],
                "team_format": "5v5",
                "queue_type": "ranked",
                "ranked_tier": "pro",
                "player_level": 45,
            },
        },
        "PartyJoinRequest": {
            "payload": {
                "party_id": "party_001",
                "region": "EU",
                "members": [
                    {"user_id": 111, "positions": ["CM", "LM"], "player_level": 45},
                    {"user_id": 222, "positions": ["FW"], "player_level": 48},
                ],
                "team_format": "7v7",
                "queue_type": "ranked",
                "ranked_tier": "pro",
            },
        },
        "LeaveRequest": {"user_id": 123456789},
        "RegionStatsRequest": {
            "region": "EU",
            "queue_type": "regular",
            "ranked_tier": None,
            "team_format": "5v5",
        },
        "QueueListRequest": {
            "region": "EU",
            "queue_type": "regular",
            "ranked_tier": None,
            "team_format": "5v5",
            "page": 1,
            "page_size": 10,
        },
        "ManualJoinRequest": {
            "user_id": 123456789,
            "queue_code": "eu_01",
            "positions": ["GK", "CB"],
            "team_format": "5v5",
            "queue_type": "regular",
            "ranked_tier": None,
            "player_level": 32,
        },
        "ReserveRequest": {"job_id": "abc-xyz-reserved-server-id"},
        "TestForceStartRequest": {"job_id": "test-job-123"},
    }

    out = Path(__file__).resolve().parent.parent / "docs" / "PAYLOAD_EXAMPLES.txt"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = ["# Schema → Example Payloads (dict style)\n", "# Generated by scripts/generate_payload_examples.py\n"]
    for name, data in examples.items():
        if isinstance(data, dict) and "payload" in data:
            body = data["payload"]
        elif isinstance(data, dict) and "regular" in data:
            body = data["regular"]
        else:
            body = data
        lines.append(f"## {name}\n")
        lines.append(json.dumps(body, indent=2))
        lines.append("\n")
        if isinstance(data, dict) and "ranked" in data:
            lines.append(f"### {name} (ranked variant)\n")
            lines.append(json.dumps(data["ranked"], indent=2))
            lines.append("\n")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
